title: ""
tagline: ""
masthead_title: false
logo: ""   # ensures no logo/title shows
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"   
plugins:
  - jekyll-include-cache

include:
  - _pages

author:
  name: ""
  avatar: "/assets/images/headshot.jpg"
  bio: "Filmmaker | Storyteller | Visual Artist"

sass:
  style: compressed

navigation: main
