title: "Darwin Froese ~ Film Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"   
plugins:
  - jekyll-include-cache

author:
  name: "Darwin Froese"
  avatar: "/assets/images/headshot.jpg"
  bio: "Filmmaker | Storyteller | Visual Artist"

sass:
  style: compressed
include:
  - assets/css/custom.css
